apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-profiling.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-profiling.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "data-profiling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-profiling.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "data-profiling.fullname" . }}-env
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 15
